-- Update Vietnamese names for countries table
-- Assumes columns: name (exact English name), name (Vietnamese name)
BEGIN;

UPDATE countries SET name = 'Afghanistan' WHERE name = 'Afghanistan';
UPDATE countries SET name = 'Quần đảo Åland' WHERE name = 'Åland Islands';
UPDATE countries SET name = 'Albania' WHERE name = 'Albania';
UPDATE countries SET name = 'Algeria' WHERE name = 'Algeria';
UPDATE countries SET name = 'Samoa thuộc Mỹ' WHERE name = 'American Samoa';
UPDATE countries SET name = 'Andorra' WHERE name = 'Andorra';
UPDATE countries SET name = 'Angola' WHERE name = 'Angola';
UPDATE countries SET name = 'Anguilla' WHERE name = 'Anguilla';
UPDATE countries SET name = 'Nam Cực' WHERE name = 'Antarctica';
UPDATE countries SET name = 'Antigua và Barbuda' WHERE name = 'Antigua and Barbuda';
UPDATE countries SET name = 'Argentina' WHERE name = 'Argentina';
UPDATE countries SET name = 'Armenia' WHERE name = 'Armenia';
UPDATE countries SET name = 'Aruba' WHERE name = 'Aruba';
UPDATE countries SET name = 'Úc' WHERE name = 'Australia';
UPDATE countries SET name = 'Áo' WHERE name = 'Austria';
UPDATE countries SET name = 'Azerbaijan' WHERE name = 'Azerbaijan';
UPDATE countries SET name = 'Bahamas' WHERE name = 'Bahamas';
UPDATE countries SET name = 'Bahrain' WHERE name = 'Bahrain';
UPDATE countries SET name = 'Bangladesh' WHERE name = 'Bangladesh';
UPDATE countries SET name = 'Barbados' WHERE name = 'Barbados';
UPDATE countries SET name = 'Belarus' WHERE name = 'Belarus';
UPDATE countries SET name = 'Bỉ' WHERE name = 'Belgium';
UPDATE countries SET name = 'Belize' WHERE name = 'Belize';
UPDATE countries SET name = 'Benin' WHERE name = 'Benin';
UPDATE countries SET name = 'Bermuda' WHERE name = 'Bermuda';
UPDATE countries SET name = 'Bhutan' WHERE name = 'Bhutan';
UPDATE countries SET name = 'Bolivia' WHERE name = 'Bolivia (Plurinational State of)';
UPDATE countries SET name = 'Bonaire, Sint Eustatius và Saba' WHERE name = 'Bonaire, Sint Eustatius and Saba';
UPDATE countries SET name = 'Bosnia và Herzegovina' WHERE name = 'Bosnia and Herzegovina';
UPDATE countries SET name = 'Botswana' WHERE name = 'Botswana';
UPDATE countries SET name = 'Đảo Bouvet' WHERE name = 'Bouvet Island';
UPDATE countries SET name = 'Brazil' WHERE name = 'Brazil';
UPDATE countries SET name = 'Lãnh thổ Ấn Độ Dương thuộc Anh' WHERE name = 'British Indian Ocean Territory';
UPDATE countries SET name = 'Brunei' WHERE name = 'Brunei Darussalam';
UPDATE countries SET name = 'Bulgaria' WHERE name = 'Bulgaria';
UPDATE countries SET name = 'Burkina Faso' WHERE name = 'Burkina Faso';
UPDATE countries SET name = 'Burundi' WHERE name = 'Burundi';
UPDATE countries SET name = 'Cabo Verde' WHERE name = 'Cabo Verde';
UPDATE countries SET name = 'Campuchia' WHERE name = 'Cambodia';
UPDATE countries SET name = 'Cameroon' WHERE name = 'Cameroon';
UPDATE countries SET name = 'Canada' WHERE name = 'Canada';
UPDATE countries SET name = 'Quần đảo Cayman' WHERE name = 'Cayman Islands';
UPDATE countries SET name = 'Cộng hòa Trung Phi' WHERE name = 'Central African Republic';
UPDATE countries SET name = 'Tchad' WHERE name = 'Chad';
UPDATE countries SET name = 'Chile' WHERE name = 'Chile';
UPDATE countries SET name = 'Trung Quốc' WHERE name = 'China';
UPDATE countries SET name = 'Đảo Giáng Sinh' WHERE name = 'Christmas Island';
UPDATE countries SET name = 'Quần đảo Cocos (Keeling)' WHERE name = 'Cocos (Keeling) Islands';
UPDATE countries SET name = 'Colombia' WHERE name = 'Colombia';
UPDATE countries SET name = 'Comoros' WHERE name = 'Comoros';
UPDATE countries SET name = 'Congo' WHERE name = 'Congo';
UPDATE countries SET name = 'Cộng hòa Dân chủ Congo' WHERE name = 'Congo (Democratic Republic of the)';
UPDATE countries SET name = 'Quần đảo Cook' WHERE name = 'Cook Islands';
UPDATE countries SET name = 'Costa Rica' WHERE name = 'Costa Rica';
UPDATE countries SET name = 'Bờ Biển Ngà' WHERE name = 'Côte d’Ivoire';
UPDATE countries SET name = 'Croatia' WHERE name = 'Croatia';
UPDATE countries SET name = 'Cuba' WHERE name = 'Cuba';
UPDATE countries SET name = 'Curaçao' WHERE name = 'Curaçao';
UPDATE countries SET name = 'Síp' WHERE name = 'Cyprus';
UPDATE countries SET name = 'Cộng hòa Séc' WHERE name = 'Czechia';
UPDATE countries SET name = 'Đan Mạch' WHERE name = 'Denmark';
UPDATE countries SET name = 'Djibouti' WHERE name = 'Djibouti';
UPDATE countries SET name = 'Dominica' WHERE name = 'Dominica';
UPDATE countries SET name = 'Cộng hòa Dominica' WHERE name = 'Dominican Republic';
UPDATE countries SET name = 'Ecuador' WHERE name = 'Ecuador';
UPDATE countries SET name = 'Ai Cập' WHERE name = 'Egypt';
UPDATE countries SET name = 'El Salvador' WHERE name = 'El Salvador';
UPDATE countries SET name = 'Guinea Xích Đạo' WHERE name = 'Equatorial Guinea';
UPDATE countries SET name = 'Eritrea' WHERE name = 'Eritrea';
UPDATE countries SET name = 'Estonia' WHERE name = 'Estonia';
UPDATE countries SET name = 'Eswatini' WHERE name = 'Eswatini';
UPDATE countries SET name = 'Ethiopia' WHERE name = 'Ethiopia';
UPDATE countries SET name = 'Quần đảo Falkland (Malvinas)' WHERE name = 'Falkland Islands (Malvinas)';
UPDATE countries SET name = 'Quần đảo Faroe' WHERE name = 'Faroe Islands';
UPDATE countries SET name = 'Fiji' WHERE name = 'Fiji';
UPDATE countries SET name = 'Phần Lan' WHERE name = 'Finland';
UPDATE countries SET name = 'Pháp' WHERE name = 'France';
UPDATE countries SET name = 'Guiana thuộc Pháp' WHERE name = 'French Guiana';
UPDATE countries SET name = 'Polynesia thuộc Pháp' WHERE name = 'French Polynesia';
UPDATE countries SET name = 'Lãnh thổ Nam thuộc Pháp' WHERE name = 'French Southern Territories';
UPDATE countries SET name = 'Gabon' WHERE name = 'Gabon';
UPDATE countries SET name = 'Gambia' WHERE name = 'Gambia';
UPDATE countries SET name = 'Georgia' WHERE name = 'Georgia';
UPDATE countries SET name = 'Đức' WHERE name = 'Germany';
UPDATE countries SET name = 'Ghana' WHERE name = 'Ghana';
UPDATE countries SET name = 'Gibraltar' WHERE name = 'Gibraltar';
UPDATE countries SET name = 'Hy Lạp' WHERE name = 'Greece';
UPDATE countries SET name = 'Greenland' WHERE name = 'Greenland';
UPDATE countries SET name = 'Grenada' WHERE name = 'Grenada';
UPDATE countries SET name = 'Guadeloupe' WHERE name = 'Guadeloupe';
UPDATE countries SET name = 'Guam' WHERE name = 'Guam';
UPDATE countries SET name = 'Guatemala' WHERE name = 'Guatemala';
UPDATE countries SET name = 'Guernsey' WHERE name = 'Guernsey';
UPDATE countries SET name = 'Guinea' WHERE name = 'Guinea';
UPDATE countries SET name = 'Guinea-Bissau' WHERE name = 'Guinea-Bissau';
UPDATE countries SET name = 'Guyana' WHERE name = 'Guyana';
UPDATE countries SET name = 'Haiti' WHERE name = 'Haiti';
UPDATE countries SET name = 'Đảo Heard và quần đảo McDonald' WHERE name = 'Heard Island and McDonald Islands';
UPDATE countries SET name = 'Tòa Thánh' WHERE name = 'Holy See';
UPDATE countries SET name = 'Honduras' WHERE name = 'Honduras';
UPDATE countries SET name = 'Hồng Kông' WHERE name = 'Hong Kong';
UPDATE countries SET name = 'Hungary' WHERE name = 'Hungary';
UPDATE countries SET name = 'Iceland' WHERE name = 'Iceland';
UPDATE countries SET name = 'Ấn Độ' WHERE name = 'India';
UPDATE countries SET name = 'Indonesia' WHERE name = 'Indonesia';
UPDATE countries SET name = 'Iran' WHERE name = 'Iran (Islamic Republic of)';
UPDATE countries SET name = 'Iraq' WHERE name = 'Iraq';
UPDATE countries SET name = 'Ireland' WHERE name = 'Ireland';
UPDATE countries SET name = 'Đảo Man' WHERE name = 'Isle of Man';
UPDATE countries SET name = 'Israel' WHERE name = 'Israel';
UPDATE countries SET name = 'Ý' WHERE name = 'Italy';
UPDATE countries SET name = 'Jamaica' WHERE name = 'Jamaica';
UPDATE countries SET name = 'Nhật Bản' WHERE name = 'Japan';
UPDATE countries SET name = 'Jersey' WHERE name = 'Jersey';
UPDATE countries SET name = 'Jordan' WHERE name = 'Jordan';
UPDATE countries SET name = 'Kazakhstan' WHERE name = 'Kazakhstan';
UPDATE countries SET name = 'Kenya' WHERE name = 'Kenya';
UPDATE countries SET name = 'Kiribati' WHERE name = 'Kiribati';
UPDATE countries SET name = 'Triều Tiên' WHERE name = 'Korea (Democratic People’s Republic of)';
UPDATE countries SET name = 'Hàn Quốc' WHERE name = 'Korea (Republic of)';
UPDATE countries SET name = 'Kuwait' WHERE name = 'Kuwait';
UPDATE countries SET name = 'Kyrgyzstan' WHERE name = 'Kyrgyzstan';
UPDATE countries SET name = 'Lào' WHERE name = 'Lao People’s Democratic Republic';
UPDATE countries SET name = 'Latvia' WHERE name = 'Latvia';
UPDATE countries SET name = 'Lebanon' WHERE name = 'Lebanon';
UPDATE countries SET name = 'Lesotho' WHERE name = 'Lesotho';
UPDATE countries SET name = 'Liberia' WHERE name = 'Liberia';
UPDATE countries SET name = 'Libya' WHERE name = 'Libya';
UPDATE countries SET name = 'Liechtenstein' WHERE name = 'Liechtenstein';
UPDATE countries SET name = 'Lithuania' WHERE name = 'Lithuania';
UPDATE countries SET name = 'Luxembourg' WHERE name = 'Luxembourg';
UPDATE countries SET name = 'Ma Cao' WHERE name = 'Macao';
UPDATE countries SET name = 'Madagascar' WHERE name = 'Madagascar';
UPDATE countries SET name = 'Malawi' WHERE name = 'Malawi';
UPDATE countries SET name = 'Malaysia' WHERE name = 'Malaysia';
UPDATE countries SET name = 'Maldives' WHERE name = 'Maldives';
UPDATE countries SET name = 'Mali' WHERE name = 'Mali';
UPDATE countries SET name = 'Malta' WHERE name = 'Malta';
UPDATE countries SET name = 'Quần đảo Marshall' WHERE name = 'Marshall Islands';
UPDATE countries SET name = 'Martinique' WHERE name = 'Martinique';
UPDATE countries SET name = 'Mauritania' WHERE name = 'Mauritania';
UPDATE countries SET name = 'Mauritius' WHERE name = 'Mauritius';
UPDATE countries SET name = 'Mayotte' WHERE name = 'Mayotte';
UPDATE countries SET name = 'Mexico' WHERE name = 'Mexico';
UPDATE countries SET name = 'Liên bang Micronesia' WHERE name = 'Micronesia (Federated States of)';
UPDATE countries SET name = 'Moldova' WHERE name = 'Moldova (Republic of)';
UPDATE countries SET name = 'Monaco' WHERE name = 'Monaco';
UPDATE countries SET name = 'Mông Cổ' WHERE name = 'Mongolia';
UPDATE countries SET name = 'Montenegro' WHERE name = 'Montenegro';
UPDATE countries SET name = 'Montserrat' WHERE name = 'Montserrat';
UPDATE countries SET name = 'Morocco' WHERE name = 'Morocco';
UPDATE countries SET name = 'Mozambique' WHERE name = 'Mozambique';
UPDATE countries SET name = 'Myanmar' WHERE name = 'Myanmar';
UPDATE countries SET name = 'Namibia' WHERE name = 'Namibia';
UPDATE countries SET name = 'Nauru' WHERE name = 'Nauru';
UPDATE countries SET name = 'Nepal' WHERE name = 'Nepal';
UPDATE countries SET name = 'Hà Lan' WHERE name = 'Netherlands';
UPDATE countries SET name = 'New Caledonia' WHERE name = 'New Caledonia';
UPDATE countries SET name = 'New Zealand' WHERE name = 'New Zealand';
UPDATE countries SET name = 'Nicaragua' WHERE name = 'Nicaragua';
UPDATE countries SET name = 'Niger' WHERE name = 'Niger';
UPDATE countries SET name = 'Nigeria' WHERE name = 'Nigeria';
UPDATE countries SET name = 'Niue' WHERE name = 'Niue';
UPDATE countries SET name = 'Đảo Norfolk' WHERE name = 'Norfolk Island';
UPDATE countries SET name = 'Bắc Macedonia' WHERE name = 'North Macedonia';
UPDATE countries SET name = 'Quần đảo Bắc Mariana' WHERE name = 'Northern Mariana Islands';
UPDATE countries SET name = 'Na Uy' WHERE name = 'Norway';
UPDATE countries SET name = 'Oman' WHERE name = 'Oman';
UPDATE countries SET name = 'Pakistan' WHERE name = 'Pakistan';
UPDATE countries SET name = 'Palau' WHERE name = 'Palau';
UPDATE countries SET name = 'Palestine' WHERE name = 'Palestine, State of';
UPDATE countries SET name = 'Panama' WHERE name = 'Panama';
UPDATE countries SET name = 'Papua New Guinea' WHERE name = 'Papua New Guinea';
UPDATE countries SET name = 'Paraguay' WHERE name = 'Paraguay';
UPDATE countries SET name = 'Peru' WHERE name = 'Peru';
UPDATE countries SET name = 'Philippines' WHERE name = 'Philippines';
UPDATE countries SET name = 'Pitcairn' WHERE name = 'Pitcairn';
UPDATE countries SET name = 'Ba Lan' WHERE name = 'Poland';
UPDATE countries SET name = 'Bồ Đào Nha' WHERE name = 'Portugal';
UPDATE countries SET name = 'Puerto Rico' WHERE name = 'Puerto Rico';
UPDATE countries SET name = 'Qatar' WHERE name = 'Qatar';
UPDATE countries SET name = 'Réunion' WHERE name = 'Réunion';
UPDATE countries SET name = 'Romania' WHERE name = 'Romania';
UPDATE countries SET name = 'Nga' WHERE name = 'Russian Federation';
UPDATE countries SET name = 'Rwanda' WHERE name = 'Rwanda';
UPDATE countries SET name = 'Saint Barthélemy' WHERE name = 'Saint Barthélemy';
UPDATE countries SET name = 'Saint Helena, Ascension và Tristan da Cunha' WHERE name = 'Saint Helena, Ascension and Tristan da Cunha';
UPDATE countries SET name = 'Saint Kitts và Nevis' WHERE name = 'Saint Kitts and Nevis';
UPDATE countries SET name = 'Saint Lucia' WHERE name = 'Saint Lucia';
UPDATE countries SET name = 'Saint Martin (Pháp)' WHERE name = 'Saint Martin (French part)';
UPDATE countries SET name = 'Saint Pierre và Miquelon' WHERE name = 'Saint Pierre and Miquelon';
UPDATE countries SET name = 'Saint Vincent và Grenadines' WHERE name = 'Saint Vincent and the Grenadines';
UPDATE countries SET name = 'Samoa' WHERE name = 'Samoa';
UPDATE countries SET name = 'San Marino' WHERE name = 'San Marino';
UPDATE countries SET name = 'São Tomé và Príncipe' WHERE name = 'Sao Tome and Principe';
UPDATE countries SET name = 'Ả Rập Xê Út' WHERE name = 'Saudi Arabia';
UPDATE countries SET name = 'Senegal' WHERE name = 'Senegal';
UPDATE countries SET name = 'Serbia' WHERE name = 'Serbia';
UPDATE countries SET name = 'Seychelles' WHERE name = 'Seychelles';
UPDATE countries SET name = 'Sierra Leone' WHERE name = 'Sierra Leone';
UPDATE countries SET name = 'Singapore' WHERE name = 'Singapore';
UPDATE countries SET name = 'Sint Maarten (Hà Lan)' WHERE name = 'Sint Maarten (Dutch part)';
UPDATE countries SET name = 'Slovakia' WHERE name = 'Slovakia';
UPDATE countries SET name = 'Slovenia' WHERE name = 'Slovenia';
UPDATE countries SET name = 'Quần đảo Solomon' WHERE name = 'Solomon Islands';
UPDATE countries SET name = 'Somalia' WHERE name = 'Somalia';
UPDATE countries SET name = 'Nam Phi' WHERE name = 'South Africa';
UPDATE countries SET name = 'Nam Georgia và Nam Sandwich' WHERE name = 'South Georgia and the South Sandwich Islands';
UPDATE countries SET name = 'Nam Sudan' WHERE name = 'South Sudan';
UPDATE countries SET name = 'Tây Ban Nha' WHERE name = 'Spain';
UPDATE countries SET name = 'Sri Lanka' WHERE name = 'Sri Lanka';
UPDATE countries SET name = 'Sudan' WHERE name = 'Sudan';
UPDATE countries SET name = 'Suriname' WHERE name = 'Suriname';
UPDATE countries SET name = 'Svalbard và Jan Mayen' WHERE name = 'Svalbard and Jan Mayen';
UPDATE countries SET name = 'Thụy Điển' WHERE name = 'Sweden';
UPDATE countries SET name = 'Thụy Sĩ' WHERE name = 'Switzerland';
UPDATE countries SET name = 'Syria' WHERE name = 'Syrian Arab Republic';
UPDATE countries SET name = 'Đài Loan' WHERE name = 'Taiwan';
UPDATE countries SET name = 'Tajikistan' WHERE name = 'Tajikistan';
UPDATE countries SET name = 'Tanzania' WHERE name = 'Tanzania, United Republic of';
UPDATE countries SET name = 'Thái Lan' WHERE name = 'Thailand';
UPDATE countries SET name = 'Đông Timor' WHERE name = 'Timor-Leste';
UPDATE countries SET name = 'Togo' WHERE name = 'Togo';
UPDATE countries SET name = 'Tokelau' WHERE name = 'Tokelau';
UPDATE countries SET name = 'Tonga' WHERE name = 'Tonga';
UPDATE countries SET name = 'Trinidad và Tobago' WHERE name = 'Trinidad and Tobago';
UPDATE countries SET name = 'Tunisia' WHERE name = 'Tunisia';
UPDATE countries SET name = 'Thổ Nhĩ Kỳ' WHERE name = 'Türkiye';
UPDATE countries SET name = 'Turkmenistan' WHERE name = 'Turkmenistan';
UPDATE countries SET name = 'Quần đảo Turks và Caicos' WHERE name = 'Turks and Caicos Islands';
UPDATE countries SET name = 'Tuvalu' WHERE name = 'Tuvalu';
UPDATE countries SET name = 'Uganda' WHERE name = 'Uganda';
UPDATE countries SET name = 'Ukraine' WHERE name = 'Ukraine';
UPDATE countries SET name = 'UAE' WHERE name = 'United Arab Emirates';
UPDATE countries SET name = 'Vương quốc Anh' WHERE name = 'United Kingdom of Great Britain and Northern Ireland';
UPDATE countries SET name = 'Hoa Kỳ' WHERE name = 'United States of America';
UPDATE countries SET name = 'Các đảo nhỏ thuộc Hoa Kỳ' WHERE name = 'United States Minor Outlying Islands';
UPDATE countries SET name = 'Uruguay' WHERE name = 'Uruguay';
UPDATE countries SET name = 'Uzbekistan' WHERE name = 'Uzbekistan';
UPDATE countries SET name = 'Vanuatu' WHERE name = 'Vanuatu';
UPDATE countries SET name = 'Venezuela' WHERE name = 'Venezuela (Bolivarian Republic of)';
UPDATE countries SET name = 'Việt Nam' WHERE name = 'Viet Nam';
UPDATE countries SET name = 'Quần đảo Virgin (Anh)' WHERE name = 'Virgin Islands (British)';
UPDATE countries SET name = 'Quần đảo Virgin (Mỹ)' WHERE name = 'Virgin Islands (U.S.)';
UPDATE countries SET name = 'Wallis và Futuna' WHERE name = 'Wallis and Futuna';
UPDATE countries SET name = 'Tây Sahara' WHERE name = 'Western Sahara';
UPDATE countries SET name = 'Yemen' WHERE name = 'Yemen';
UPDATE countries SET name = 'Zambia' WHERE name = 'Zambia';
UPDATE countries SET name = 'Zimbabwe' WHERE name = 'Zimbabwe';

COMMIT;
